kind: Pod
apiVersion: v1

metadata:
  name: testpod4

spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Rohit; sleep 5; done"]

      env:                # List of environment variables to be used inside the container
        - name: MYNAME    #(Key name of the environment variable)
          value: Sumeet      #(Value)
