kind: Pod
apiVersion: v1

metadata:
  name: labelspod2

  labels:                    # Specifies the Label details under it
    day: sat
    class: kubernetes

spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Pod6; sleep 5; done"]
